services:
  web:
    container_name: web
    build:
      context: apps/web
      dockerfile: Dockerfile.dev
    command: pnpm -F web run dev
    env_file:
      - apps/web/.env.development
    ports:
      - 3000:3000
    volumes:
      - .:/app
  admin:
    container_name: admin
    build:
      context: apps/admin
      dockerfile: Dockerfile.dev
    command: pnpm -F admin run dev
    env_file:
      - apps/admin/.env.development
    ports:
      - 3001:3001
    volumes:
      - .:/app
