services:
  web:
    image: standardwish/web
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.prod
    restart: always
    ports:
      - 3000:3000
    env_file:
      - apps/web/.env.production
    networks:
      - app_network
  admin:
    image: standardwish/admin
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile.prod
    restart: always
    ports:
      - 3001:3001
    env_file:
      - apps/admin/.env.production
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
