import { routing } from "@/i18n/routing";
import NavLogo from "@repo/assets/images/nav_logo.png";
import { ThemeProvider } from "@repo/core/theme-provider";
import { NavBar } from "@repo/ui/features/common/navigation/nav-bar";
import type { Metadata } from "next";

import LocaleSwitcher from "@/features/locale/locale-switcher";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import Image from "next/image";
import { notFound } from "next/navigation";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { SearchParams } from "nuqs/server";
import "../globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<SearchParams>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} suppressHydrationWarning>
      <body style={{ backgroundColor: "var(--background)" }}>
        <ThemeProvider
          defaultTheme="light"
          enableColorScheme
          themes={["light", "high-contrast"]}
        >
          <NuqsAdapter>
            <NextIntlClientProvider>
              <NavBar
                logo={<Image src={NavLogo} alt="Logo" width={87} height={56} />}
                rightSlot={<LocaleSwitcher />}
                items={[
                  {
                    label: "Home",
                    href: "/",
                    active: true,
                  },
                  {
                    label: "About",
                    href: "/about",
                    active: false,
                  },
                ]}
              />
              {children}
            </NextIntlClientProvider>
          </NuqsAdapter>
        </ThemeProvider>
      </body>
    </html>
  );
}
