name: Auto Assign Issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Auto assign issues
        if: github.event_name == 'issues'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: |
            forif-npo/frontend-team
          numOfAssignee: 1

      - name: Auto assign PRs
        if: github.event_name == 'pull_request'
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/auto-assign.yml"
